GET http://localhost:3001/todos HTTP/1.1

###

POST http://localhost:3001/todo/new 
Content-Type: application/json

{
"text": "Go to Gym"
}

###

DELETE http://localhost:3001/todo/delete/631c120558988589392ee3bc"